<a href="https://colab.research.google.com/github/JoDeMiro/ImageProcessing/blob/main/96_Image_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name="tartalom"></a>

# NumPy Arrays
---
NumPy - *Vektor, Mátrix, Tensor*.

In [ ]:
import numpy as np

In [ ]:
M = np.array([
    [2, 3, 8],
    [5, 7, 6]
])
N = np.array([
    [1, 7],
    [5, 6],
    [2, 9],
])

In [ ]:
np.dot(M,N)

array([[ 33, 104],
       [ 52, 131]])

In [ ]:
np.dot(N,M)

array([[37, 52, 50],
       [40, 57, 76],
       [49, 69, 70]])

In [ ]:
image = np.array([[1,1,4],
                  [1,2,5],
                  [1,3,5],
                  [1,4,7],
                  [2,1,6],
                  [2,2,5],
                  [2,3,4],
                  [2,4,5],
                  [3,1,6],
                  [3,2,7],
                  [3,3,8],
                  [3,4,7],
                  [4,1,6],
                  [4,2,5],
                  [4,3,4],
                  [4,4,3]])

t = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

print(image.shape)
print(t.shape)

(16, 3)
(3, 3)


In [ ]:
np.dot(image,t)

array([[1, 1, 4],
       [1, 2, 5],
       [1, 3, 5],
       [1, 4, 7],
       [2, 1, 6],
       [2, 2, 5],
       [2, 3, 4],
       [2, 4, 5],
       [3, 1, 6],
       [3, 2, 7],
       [3, 3, 8],
       [3, 4, 7],
       [4, 1, 6],
       [4, 2, 5],
       [4, 3, 4],
       [4, 4, 3]])

In [ ]:
image[1]

array([1, 2, 5])

In [ ]:
image[1][2]

5

# NumPy Arrays

In [ ]:
a1 = np.arange(1,13)

a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# reshape
a1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# reshape
a1.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# reshape
a1.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# reshape
a1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# reshape
a1.reshape(3, -1, order = 'F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
# reshape
a1.reshape(3, -1, order = 'C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3D array from 2D arrays

In [ ]:
a1 = np.arange(1, 13).reshape(3, 4)
a2 = np.arange(13, 25).reshape(3, 4)

In [ ]:
print(a1)
print('')
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
# stack along axis 2
np.stack((a1, a2), axis = 2)

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [ ]:
np.stack((a1, a2), axis = 2).shape

(3, 4, 2)

In [ ]:
# stack along axis 1
np.stack((a1, a2), axis = 1)

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [ ]:
np.stack((a1, a2), axis = 1).shape

(3, 2, 4)

In [ ]:
# stack along axis 0
np.stack((a1, a2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
np.stack((a1,a2)).shape

(2, 3, 4)

# 2D matrix from 1D vector

In [ ]:
a1 = np.arange(1, 13)
a2 = np.arange(13, 25)

In [ ]:
np.stack((a1, a2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.stack((a1, a2), axis = 1)

array([[ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23],
       [12, 24]])

In [ ]:
np.stack((a1, a2), axis = 1).T

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

# Concatenate two vector

In [ ]:
np.hstack((a1, a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])


<a name="felhasznalt-irodalom"></a>

[vissza a tartalomhoz](#tartalom)

<a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>

## Felhasznált irodalom és internetes cimek <a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>


Numpy Arrays in Python
<br>
https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b


Chapter 1. Vectors, Matrices, and Arrays
<br>
https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html

Math is Fun - Vectors
<br>
https://www.mathsisfun.com/algebra/vectors.html


Wikipedia - 'Euclidean Vector'
<br>
https://en.wikipedia.org/wiki/Euclidean_vector

