<a href="https://colab.research.google.com/github/JoDeMiro/ImageProcessing/blob/main/96_Image_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name="tartalom"></a>

# NumPy Arrays
---
NumPy - *Vektor, Mátrix, Tensor*.

In [2]:
import numpy as np

In [ ]:
M = np.array([
    [2, 3, 8],
    [5, 7, 6]
])
N = np.array([
    [1, 7],
    [5, 6],
    [2, 9],
])

In [ ]:
np.dot(M,N)

array([[ 33, 104],
       [ 52, 131]])

In [ ]:
np.dot(N,M)

array([[37, 52, 50],
       [40, 57, 76],
       [49, 69, 70]])

In [ ]:
image = np.array([[1,1,4],
                  [1,2,5],
                  [1,3,5],
                  [1,4,7],
                  [2,1,6],
                  [2,2,5],
                  [2,3,4],
                  [2,4,5],
                  [3,1,6],
                  [3,2,7],
                  [3,3,8],
                  [3,4,7],
                  [4,1,6],
                  [4,2,5],
                  [4,3,4],
                  [4,4,3]])

t = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

print(image.shape)
print(t.shape)

(16, 3)
(3, 3)


In [ ]:
np.dot(image,t)

array([[1, 1, 4],
       [1, 2, 5],
       [1, 3, 5],
       [1, 4, 7],
       [2, 1, 6],
       [2, 2, 5],
       [2, 3, 4],
       [2, 4, 5],
       [3, 1, 6],
       [3, 2, 7],
       [3, 3, 8],
       [3, 4, 7],
       [4, 1, 6],
       [4, 2, 5],
       [4, 3, 4],
       [4, 4, 3]])

In [ ]:
image[1]

array([1, 2, 5])

In [ ]:
image[1][2]

5

# NumPy Arrays

In [ ]:
a1 = np.arange(1,13)

a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# reshape
a1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# reshape
a1.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# reshape
a1.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# reshape
a1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# reshape
a1.reshape(3, -1, order = 'F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
# reshape
a1.reshape(3, -1, order = 'C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3D array from 2D arrays

In [ ]:
a1 = np.arange(1, 13).reshape(3, 4)
a2 = np.arange(13, 25).reshape(3, 4)

In [ ]:
print(a1)
print('')
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
# stack along axis 2
np.stack((a1, a2), axis = 2)

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [ ]:
np.stack((a1, a2), axis = 2).shape

(3, 4, 2)

In [ ]:
# stack along axis 1
np.stack((a1, a2), axis = 1)

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [ ]:
np.stack((a1, a2), axis = 1).shape

(3, 2, 4)

In [ ]:
# stack along axis 0
np.stack((a1, a2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
np.stack((a1,a2)).shape

(2, 3, 4)

# 2D matrix from 1D vector

In [ ]:
a1 = np.arange(1, 13)
a2 = np.arange(13, 25)

In [ ]:
np.stack((a1, a2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.stack((a1, a2), axis = 1)

array([[ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23],
       [12, 24]])

In [ ]:
np.stack((a1, a2), axis = 1).T

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

# Concatenate two vector

In [ ]:
np.hstack((a1, a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# Mátrix rangja

In [3]:
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

np.linalg.matrix_rank(matrix)

2

In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.linalg.matrix_rank(matrix)

2

# Mátrix determinánsa

In [5]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

np.linalg.det(matrix)

0.0

In [9]:
matrix = np.array([[1, 1, 5],
                   [5, 1, 10],
                   [1, 1, 15]])

np.linalg.det(matrix)

-40.000000000000014

# Mátrix diagonálisa

In [11]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

np.diagonal(matrix)

array([1, 4, 9])

In [12]:
matrix.diagonal(offset=1)

array([2, 6])

In [13]:
matrix.diagonal(offset=-1)

array([2, 8])

# Trace

In [14]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

matrix.trace()

14

In [15]:
sum(matrix.diagonal())

14

# Négyzetes mátrix sajátértéke sajátvektora

A sajátvektorokat széles körben használják a machine learning könyvtárak.

Vegyünk egy lineáris transzformációt reprezentáljuk $A$ mátrixal. Ekkor a sajátvektorok azok a vektorok, amelyek ha a transzformációt vesszük nem változtatják az irányukat, csak a méretüket.

$$A v = \lambda v$$

$A$ egy négyzetes mátrix és $\lambda$ tartalmazza a sajátértékekeket és $v$ tartlamazza a sajátvektorokat.

Akkor a $A$ mátrixnak a $v$ sajátvektorokkal vett szorzata és a $\lambda$ sajátértéknek a $v$ sajátvektorokkal vett szorzata egyenlő.

In [23]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])


eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print('')
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]

[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [26]:
np.dot(matrix,eigenvectors)

array([[ -2.38791692,  -0.71544319,   1.7564039 ],
       [ -5.90746667,   0.15197456,   2.1167956 ],
       [-11.95921174,   0.11265576,  -1.80652152]])

In [25]:
eigenvalues * eigenvectors

array([[ -2.38791692,  -0.71544319,   1.7564039 ],
       [ -5.90746667,   0.15197456,   2.1167956 ],
       [-11.95921174,   0.11265576,  -1.80652152]])

# Skaláris szorzat - Dot Product

A skaláris szorzat, elemenként vagy páronként való szorzat összege:

$$\sum_{i=1}^{n}a_i*b_i$$

Vagyis $a$ vektor $i$-edik elemét megszorozzuk $b$ vektor $i$-edik elemével.


In [28]:

a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a, b)


32

In [29]:
s = 0
for i in range(len(a)):
  s += a[i] * b[i]

s

32

Használhatjuk a NumPy dot függvényént a skaláris szorzat kiszámításához, de az újabb Python verzióban már használhatjuk a @ operátort is.

In [31]:
# Python 3.5 verziójától fogva használhatjuk az alábbi operátort is

a @ b

32


<a name="felhasznalt-irodalom"></a>

[vissza a tartalomhoz](#tartalom)

<a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>

## Felhasznált irodalom és internetes cimek <a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>


Numpy Arrays in Python
<br>
https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b


Chapter 1. Vectors, Matrices, and Arrays
<br>
https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html

Math is Fun - Vectors
<br>
https://www.mathsisfun.com/algebra/vectors.html


Wikipedia - 'Euclidean Vector'
<br>
https://en.wikipedia.org/wiki/Euclidean_vector


The determinant | Essence of linear algebra, chapter 5, 3Blue1Brown
<br>
https://www.youtube.com/watch?v=Ip3X9LOh2dk


Determinant, Wolfram MathWorld
<br>
https://mathworld.wolfram.com/Determinant.html


The rank of the matrix
<br>
https://www.cliffsnotes.com/study-guides/algebra/linear-algebra/real-euclidean-vector-spaces/the-rank-of-a-matrix


Eigenvectors and Eigenvalues Explained Visually, Setosa.io
<br>
https://setosa.io/ev/eigenvectors-and-eigenvalues/


Eigenvectors and eigenvalues | Essence of linear algebra, Chapter 10, 3Blue1Brown
<br>
https://www.youtube.com/watch?v=PFDu9oVAE-g


Vector dot product and vector length, Khan Academy
<br>
https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length


Dot Product, Paul’s Online Math Notes
<br>
https://tutorial.math.lamar.edu/Classes/CalcII/DotProduct.aspx

