<a href="https://colab.research.google.com/github/JoDeMiro/ImageProcessing/blob/main/98_Line%C3%A1ris_Algebra_M%C3%A1trixok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name="tartalom"></a>

# Lineáris algebra - Mátrixok
---
Régi Linalg jegyzetem - *Mátrixok*.

In [2]:
import numpy as np

# 1. A mátrix?
---
A mátrix $ A$ egy *négyzet alakú tömb* amelynek elemei *sorokba* $m$ és *oszlopokba* $n$ vannak rendezve.


$$ \large
A = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
a_{31} & a_{32} & \cdots & a_{3n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{bmatrix}
$$

A *négyzetes mátrix* *soriainak* és *oszlopainak* száma megegyezik.

# 2. Mátrix műveletek
---
A következő műveletek minden vektorra is alkalmazhatóak amelyek $\large \mathbb{R}^{m \times n}$.

## 2.1. Mátrix összeadás
---
Két mátrix összeadásánál $\large M_{3\times2}$ és $\large N_{3\times2}$ a megfelelő elemeket kell összeadni.

$$ \large
M+N = 
\begin{bmatrix}
m_{11} & m_{12} \\
m_{21} & m_{22} \\
m_{31} & m_{32} \\
\end{bmatrix} +
\begin{bmatrix}
n_{11} & n_{12} \\
n_{21} & n_{22} \\
n_{31} & n_{32} \\
\end{bmatrix} =
\begin{bmatrix}
m_{11}+n_{11} & m_{12}+n_{12} \\
m_{21}+n_{21} & m_{22}+n_{22} \\
m_{31}+n_{31} & m_{32}+n_{32} \\
\end{bmatrix}
$$


Példa:


$$ \large
M =
\begin{bmatrix}
2 & 5 \\
3 & 7 \\
8 & 6
\end{bmatrix}
\quad , \quad
N =
\begin{bmatrix}
1 & 7 \\
5 & 6 \\
2 & 9
\end{bmatrix}
$$


$$ \large
M + N =
\begin{bmatrix}
2+1 & 5+7 \\
3+5 & 7+6 \\
8+2 & 6+9
\end{bmatrix} =
\begin{bmatrix}
3 & 12 \\
8 & 13 \\
10 & 15
\end{bmatrix}
$$

In [3]:
M = np.array([
    [2, 5],
    [3, 7],
    [8, 6],
])
N = np.array([
    [1, 7],
    [5, 6],
    [2, 9],
])
print(M, end=" = M\n\n")
print(N, end=" = N\n\n")
print(M + N, end=" = M + N")

[[2 5]
 [3 7]
 [8 6]] = M

[[1 7]
 [5 6]
 [2 9]] = N

[[ 3 12]
 [ 8 13]
 [10 15]] = M + N

### A mátrix összeadás tulajdonságai
---
1. $M + (N + P) = (M + N) + P$
2. $M + 0 = 0 + M = M$
3. $M + N = N + M$

## 2.2. Mátrix kivonás
---
Ugyan az mint a mátrix összeadásnál az $\large M$ és $\large N$ mátrix megfelelő elemeit kell kivonni egymásból.

$$ \large
M-N = 
\begin{bmatrix}
m_{11} & m_{12} \\
m_{21} & m_{22} \\
m_{31} & m_{32} \\
\end{bmatrix} -
\begin{bmatrix}
n_{11} & n_{12} \\
n_{21} & n_{22} \\
n_{31} & n_{32} \\
\end{bmatrix} =
\begin{bmatrix}
m_{11}-n_{11} & m_{12}-n_{12} \\
m_{21}-n_{21} & m_{22}-n_{22} \\
m_{31}-n_{31} & m_{32}-n_{32} \\
\end{bmatrix}
$$


Példa:


$$ \large
M =
\begin{bmatrix}
2 & 5 \\
3 & 7 \\
8 & 6
\end{bmatrix}
\quad , \quad
N =
\begin{bmatrix}
1 & 7 \\
5 & 6 \\
2 & 9
\end{bmatrix}
$$


$$ \large
M - N =
\begin{bmatrix}
2-1 & 5-7 \\
3-5 & 7-6 \\
8-2 & 6-9
\end{bmatrix} =
\begin{bmatrix}
1 & -2 \\
-2 & 1 \\
6 & -3
\end{bmatrix}
$$

In [4]:
M = np.array([
    [2, 5],
    [3, 7],
    [8, 6],
])
N = np.array([
    [1, 7],
    [5, 6],
    [2, 9],
])
print(M, end=" = M\n\n")
print(N, end=" = N\n\n")
print(M - N, end=" = M - N")

[[2 5]
 [3 7]
 [8 6]] = M

[[1 7]
 [5 6]
 [2 9]] = N

[[ 1 -2]
 [-2  1]
 [ 6 -3]] = M - N

### A mátrix kivonás tulajdonságai
---
1. $-(-M) = M$
2. $-M + M = M - M = 0$
3. $M - N \neq N - M$

## 2.3. Skalárral való szorzás
---
Skalárral való szorzásnál a mátrix minden elemét meg kell szorozni $\large \alpha$ skalárral. Ugyanígy járunk el skalárral valóö osztásnál is.

$$ \large
\alpha M = 
\alpha \cdot
\begin{bmatrix}
m_{11} & m_{12} & \cdots & m_{1n} \\
m_{21} & m_{22} & \cdots & m_{2n} \\
m_{31} & m_{32} & \cdots & m_{3n} \\
\vdots & \vdots & \ddots & \vdots \\
m_{m1} & m_{m2} & \cdots & m_{mn}
\end{bmatrix} =
\begin{bmatrix}
\alpha \cdot m_{11} & \alpha \cdot m_{12} & \cdots & \alpha \cdot m_{1n} \\
\alpha \cdot m_{21} & \alpha \cdot m_{22} & \cdots & \alpha \cdot m_{2n} \\
\alpha \cdot m_{31} & \alpha \cdot m_{32} & \cdots & \alpha \cdot m_{3n} \\
\vdots & \vdots & \ddots & \vdots \\
\alpha \cdot m_{m1} & \alpha \cdot m_{m2} & \cdots & \alpha \cdot m_{mn}
\end{bmatrix}
$$


Példa:

$$ \large
\alpha = 2
\quad , \quad
M =
\begin{bmatrix}
2 & 5 \\
3 & 7 \\
8 & 6
\end{bmatrix}
$$

$$ \large
\alpha \cdot M =
\begin{bmatrix}
2 \cdot 2 & 2 \cdot 5 \\
2 \cdot 3 & 2 \cdot 7 \\
2 \cdot 8 & 2 \cdot 6
\end{bmatrix} =
\begin{bmatrix}
4 & 10 \\
6 & 14 \\
16 & 12
\end{bmatrix}
$$

In [5]:
a = 2
M = np.array([
    [2, 5],
    [3, 7],
    [8, 6],
])
print(a, end=" = a\n\n")
print(M, end=" = M\n\n")
print(a*M, end=" = a.M")

2 = a

[[2 5]
 [3 7]
 [8 6]] = M

[[ 4 10]
 [ 6 14]
 [16 12]] = a.M

### A skalárral való szorzás tulajdonságai
---
1. $(\alpha \beta) M = \alpha (\beta M)$
2. $(\alpha + \beta) M = \alpha M + \beta M$
3. $\alpha(M + N) = \alpha M + \alpha N$
4. $1M = M$

# 3. Mátrix szorzás
---
Két mátrix $\large M_{m \times n}$ és $\large N_{n \times p}$ összeszorzásakor az a szabály, hogy az *első mátrix* oszlopainak száma (${m \times n}$) meg kell, hogy egyezzen a *második mátrix* (${n \times p}$) sorainak számával. Az eredmény egy másik (${m \times p}$) méretű mátrix lesz.

$$ \large
[MN]_{ij}=m_{i1} \cdot n_{1j}+m_{i2} \cdot n_{2j}+ \cdots + m_{in} \cdot n_{nj}=\sum_1^n m_{in} \cdot m_{nj}
$$


Példa


$$ \large
M =
\begin{bmatrix}
2 & 3 & 8 \\
5 & 7 & 6
\end{bmatrix}
\quad , \quad
N =
\begin{bmatrix}
1 & 7 \\
5 & 6 \\
2 & 9
\end{bmatrix}
$$


$$ \large
M \times N =
\begin{bmatrix}
2 \cdot 1 + 3 \cdot 5 + 8 \cdot 2 & 2 \cdot 7 + 3 \cdot 6 + 8 \cdot 9 \\
5 \cdot 1 + 7 \cdot 5 + 6 \cdot 2 & 5 \cdot 7 + 7 \cdot 6 + 6 \cdot 9
\end{bmatrix} =
\begin{bmatrix}
33 & 104 \\
52 & 131
\end{bmatrix}
$$

In [6]:
M = np.array([
    [2, 3, 8],
    [5, 7, 6]
])
N = np.array([
    [1, 7],
    [5, 6],
    [2, 9],
])
print(M, end=" = M\n\n")
print(N, end=" = N\n\n")
print(np.dot(M, N), end=" = M x N")

[[2 3 8]
 [5 7 6]] = M

[[1 7]
 [5 6]
 [2 9]] = N

[[ 33 104]
 [ 52 131]] = M x N

### A mátrix szorzás tulajdonságai
---
1. $M_{m \times n} N_{n \times m} \neq N_{n \times m} M_{m \times n}$
2. $(M_{m \times n} N_{n \times p}) P_{p \times q} = M_{m \times n}(N_{n \times p} P_{p \times q})$
3. $(M_{m \times n} + N_{m \times n}) P_{n \times p} = M_{m \times n}P_{n \times p} + N_{m \times n}P_{n \times p}$
4. $P_{m \times n} (M_{n \times p} + N_{n \times p}) = P_{m \times n} M_{n \times p} + P_{m \times n} N_{n \times p}$
5. $(\alpha M_{m \times n}) N_{n \times p} = M_{m \times n} (\alpha N_{n \times p}) = \alpha (M_{m \times n} N_{n \times p})$

# 4. Mátrix transponáltja
---
A mátrix *transponálás* egy olyan művelet ami a mátrix soraiból oszlopokat az oszlopokból sorokat csinál, tehát $M_{m \times n}^T = M_{n \times m}$.

Például:

$$ \large
\begin{bmatrix}
1 & 7 \\
5 & 6 \\
2 & 9
\end{bmatrix}^T =
\begin{bmatrix}
1 & 5 & 2 \\
7 & 6 & 9
\end{bmatrix}
$$

In [7]:
M = np.array([
    [1, 7],
    [5, 6],
    [2, 9],
])
print(M, end=" = M\n\n")
print(M.T, end=" = MT")

[[1 7]
 [5 6]
 [2 9]] = M

[[1 5 2]
 [7 6 9]] = MT

### A mátrix transponálás tulajdonságai
---
1. $(M + N)^T = M^T + N^T$
2. $(\alpha M)^T = \alpha M^T$
3. $(M^T)^T = M$
4. $(M_{m \times n} N_{n \times p})^T = N_{n \times p}^T M_{m \times n}^T$

# 5. A mátrix determinánsa
---
A *négyzetes mátrix* determinánsa ($\det(M)$ vagy másféleképen $|M|$) egy olyan művelet amely, a mátrixból előálít egy *valós számot*.

A mátrix minden sorából és oszlopából kiválasztunk egy és csak egy elemet, és ezeket az elemeket összeszorozzuk. Ezt az összes lehetséges módon megtesszük és a s szorzatokat ellátjuk egy előjellel. Végül az így kapott előjeles szorzatokat összeadjuk.

<br>

$$ \large
\det (M_{2 \times 2}) =
\det \begin{bmatrix}
a & b \\
c & d
\end{bmatrix} =
a d - b c
$$

vagy
<br>


$$ \large
\det (M_{2 \times 2}) =
\det \begin{bmatrix}
m_{11} & m_{12} \\
m_{21} & m_{22}
\end{bmatrix} =
m_{11} m_{22} - m_{12} m_{21}
$$


<br>

Például:

$$ \large
\begin{aligned}
M & =
\begin{bmatrix}
3 & 5  \\
2 & 7
\end{bmatrix} \\
|M| & =
(3 \cdot 7 - 5 \cdot 2) \\
|M| & = 21 - 10 \\
|M| & = 11
\end{aligned}
$$

<br>

Egy $3 \times 3$ mátrixot véve:


$$ \large
\begin{aligned}
|M_{3 \times 3}| & =
\det \begin{bmatrix}
m_{11} & m_{12} & m_{13} \\
m_{21} & m_{22} & m_{23} \\
m_{31} & m_{32} & m_{33}
\end{bmatrix} \\
|M_{3 \times 3}| & =
(m_{11} m_{22} m_{33} + m_{12} m_{23} m_{31} + m_{13} m_{21} m_{32}) - (m_{13} m_{22} m_{31} + m_{12} m_{21} m_{33} + m_{11} m_{23} m_{32})
\end{aligned}
$$

<br>

Például:

$$ \large
\begin{aligned}
M & =
\begin{bmatrix}
1 & 7 & 3 \\
5 & 6 & 8 \\
2 & 9 & 4
\end{bmatrix} \\
|M| & =
(1 \cdot 6 \cdot 4 + 7 \cdot 8 \cdot 2 + 3 \cdot 5 \cdot 9) - (3 \cdot 6 \cdot 2 + 7 \cdot 5 \cdot 4 + 1 \cdot 8 \cdot 9) \\
|M| & = (24 + 112 + 135) - (36 + 140 + 72) \\
|M| & = 271 - 248 \\
|M| & = 23
\end{aligned}
$$

In [9]:
M = np.array([
    [3, 5],
    [2, 7],
])
print(M, end=" = M\n\n")
print(round(np.linalg.det(M)), end=" = |M|")

[[3 5]
 [2 7]] = M

11 = |M|

In [8]:
M = np.array([
    [1, 7, 3],
    [5, 6, 8],
    [2, 9, 4],
])
print(M, end=" = M\n\n")
print(round(np.linalg.det(M)), end=" = |M|")

[[1 7 3]
 [5 6 8]
 [2 9 4]] = M

23 = |M|

### A mátrix determinánsának tulajdonságai
---
1. $|M^T| = |M|$
2. $|MN| = |M| |N|$

# 6. Identitás mátrix
---
Az *identitás mátrix* $I_n$ egy olyan *négyzetes mátrix* amelynek elemei a *főátlóban* egyenlőek 1-el és minden más elem egyenlő 0-val.

$$ \large
I_1 = 
\begin{bmatrix}
1
\end{bmatrix}
\quad , \quad
I_2 = 
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
\quad , \quad
I_3 = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\quad , \quad
I_n = 
\begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{bmatrix}
$$

In [10]:
I2 = np.eye(2)
I3 = np.eye(3)
I4 = np.eye(4)
print(I2, end=" = I2\n\n")
print(I3, end=" = I3\n\n")
print(I4, end=" = I4\n\n")

[[1. 0.]
 [0. 1.]] = I2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I3

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] = I4



### Az identitás mátirx tulajdonságai
---
1. $M_{m \times n} I_n = I_m M_{m \times n} = M$
2. $I_n^T = I_n$

# 7. Mátrix inverze
---

A lineáris algebrában egy $A_{n \times n}$-es *négyzetes* $A$ mátrix invertálható, reguláris, nemelfajuló vagy nem szinguláris, ha létezik egy olyan $B_{n \times n}$-es $B$ mátrix, melyre igaz:

1. $AB = BA = I$
2. Nem lehet szinguláris mátrix, azaz $|A| \neq 0$


$B$ mátirx $A$ mátrix inverze és $A^{-1}$, és azt jelenti, hogy $A$ mátrixot megszorozva a saját inverzével identitás mátrixot kapunk, $A A^{-1} = I$.


Például


$$ \large
A =
\begin{bmatrix}
2 & 1 & 0 \\
0 & 1 & 0 \\
1 & 2 & 1
\end{bmatrix} 
$$

tehát,

$$ \large
A A^{-1} = I_3
\quad \Rightarrow \quad
\begin{bmatrix}
2 & 1 & 0 \\
0 & 1 & 0 \\
1 & 2 & 1
\end{bmatrix}
\begin{bmatrix}
m_{11} & m_{12} & m_{13} \\
m_{21} & m_{22} & m_{23} \\
m_{31} & m_{32} & m_{33}
\end{bmatrix} =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

$$ \large
\begin{bmatrix}
2 m_{11} + m_{21} & 2 m_{12} + m_{22} & 2 m_{13} + m_{23} \\
m_{21} & m_{22} & m_{23} \\
m_{11} + 2 m_{21} + m_{31} & m_{12} + 2 m_{22} + m_{32} & m_{13} + 2 m_{23} + m_{33}
\end{bmatrix} = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

<br>

Miután megoldottuk ezt a egyenletet (például Cramer féle szabállyal) az eredményünk a következő lesz:

<br>

$$ \large
M^{-1} = 
\begin{bmatrix}
\frac{1}{2} & - \frac{1}{2} & 0 \\
0 & 1 & 0 \\
- \frac{1}{2} & - \frac{3}{2} & 1
\end{bmatrix}
$$

In [11]:
M = np.array([
    [2, 1, 0],
    [0, 1, 0],
    [1, 2, 1],
])
print(M, end=" = M\n\n")
print(np.linalg.inv(M), end=" = |M|")

[[2 1 0]
 [0 1 0]
 [1 2 1]] = M

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = |M|


<a name="felhasznalt-irodalom"></a>

[vissza a tartalomhoz](#tartalom)

<a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>

## Felhasznált irodalom és internetes cimek <a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>


------------

Mateking - Lineáris algebra - 'Determináns, sajátérték, sajátvektor'
<br>
https://www.mateking.hu/linearis-algebra/determinans-sajatertek-sajatvektor/mi-az-a-determinans#4


Wikipedia - 'Determináns'
<br>
https://hu.wikipedia.org/wiki/Determin%C3%A1ns_(matematika)


Wikikönyvek - 'Determináns'
<br>
https://hu.wikibooks.org/wiki/Matematika/M%C3%A1trix/Determin%C3%A1ns


Wikipedia - 'Determináns'
<br>
https://hu.wikipedia.org/wiki/Invert%C3%A1lhat%C3%B3_m%C3%A1trix


Mateking - Lineáris algebra - 'Determináns, sajátérték, sajátvektor'
<br>
https://www.mateking.hu/matematika-gti/linearis-algebra/matrix-inverze-negyzetes-matrixoknal-gauss


Kis-Tóth Ágnes - ELTE Természettudományi Kar
<br>
http://skiszkao.web.elte.hu/vektor/Inverz_determinans(1).pdf