<a href="https://colab.research.google.com/github/JoDeMiro/ImageProcessing/blob/main/99_Line%C3%A1ris_Algebra_Vektorok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lineáris algebra - Vektorok
---
Régi Linalg jegyzetem - *Vektorok*.

In [ ]:
import numpy as np

# 1. Mi a vektor?
---
A vektor $\large \vec{v}$ matematikia fogalom amelynek van *nagysága* és *iránya*.

![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors.jpg?raw=true)



# 2. Vektor műveletek
---
Bármely vektorra alakalmazhatóak $\large \mathbb{R}^n$.

## 2.1. Összeadás
---
Két vektor $\large \vec{u}$ és $\large \vec{v}$ összeadásánál a megfeleő elemeket összeadjuk.

$$ \large
\vec{u}+\vec{v} = 
\begin{bmatrix}
u_1 \\ u_2 \\ \vdots \\ u_n
\end{bmatrix} +
\begin{bmatrix}
v_1 \\ v_2 \\ \vdots \\ v_n
\end{bmatrix} =
\begin{bmatrix}
v_1 + u_1 \\ v_2 + u_2 \\ \vdots \\ v_n + u_n
\end{bmatrix}
$$


![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_addition.jpg?raw=true)


Például:

$$ \large
\vec{u} =
\begin{bmatrix}
3 \\ 7
\end{bmatrix}
\quad , \quad
\vec{v} =
\begin{bmatrix}
2 \\ 5
\end{bmatrix}
$$

$$ \large
\vec{u} + \vec{v} =
\begin{bmatrix}
3 + 2 \\ 7 + 5
\end{bmatrix} =
\begin{bmatrix}
5 \\ 12
\end{bmatrix}
$$

In [ ]:
u = np.array([[3, 7]])
v = np.array([[2, 5]])
print(u.T, end=" = u\n\n")
print(v.T, end=" = v\n\n")
print((u + v).T, end=" = u + v")

[[3]
 [7]] = u

[[2]
 [5]] = v

[[ 5]
 [12]] = u + v

## 2.2. Kivonás
---
Ugyan az mint az összeadásnál csak itt kivonjuk $\large \vec{u}$ és $\large \vec{v}$ a megfelelő elemeket.

$$ \large
\vec{u}-\vec{v} = 
\begin{bmatrix}
u_1 \\ u_2 \\ \vdots \\ u_n
\end{bmatrix} -
\begin{bmatrix}
v_1 \\ v_2 \\ \vdots \\ v_n
\end{bmatrix} =
\begin{bmatrix}
v_1 - u_1 \\ v_2 - u_2 \\ \vdots \\ v_n - u_n
\end{bmatrix}
$$

![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_subtraction.jpg?raw=true)

Példa:

$$ \large
\vec{u} =
\begin{bmatrix}
3 \\ 7
\end{bmatrix}
\quad , \quad
\vec{v} =
\begin{bmatrix}
2 \\ 5
\end{bmatrix}
$$

$$ \large
\vec{u} - \vec{v} =
\begin{bmatrix}
3 - 2 \\ 7 - 5
\end{bmatrix} =
\begin{bmatrix}
1 \\ 2
\end{bmatrix}
$$

In [ ]:
u = np.array([[3, 7]])
v = np.array([[2, 5]])
print(u.T, end=" = u\n\n")
print(v.T, end=" = v\n\n")
print((u - v).T, end=" = u - v")

[[3]
 [7]] = u

[[2]
 [5]] = v

[[1]
 [2]] = u - v

## 2.3. Skalárra való szorzás
---
A vektor elemeit egyenként megszorozzuk a skalárral $\large \alpha$. Ugyanez a szabály érvényes az osztásra is.

$$ \large
\alpha\vec{u} = 
\alpha  \cdot
\begin{bmatrix}
u_1 \\ u_2 \\ \vdots \\ u_n
\end{bmatrix} =
\begin{bmatrix}
\alpha\cdot u_1 \\ \alpha\cdot u_2 \\ \vdots \\ \alpha\cdot u_n
\end{bmatrix}
$$


![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_scalar_multiplication.jpg?raw=true)



Példa

$$ \large
\alpha = 2
\quad , \quad
\vec{u} =
\begin{bmatrix}
3 \\ 7
\end{bmatrix}
$$

$$ \large
\alpha\cdot\vec{u} =
\begin{bmatrix}
2 \cdot 3 \\ 2 \cdot 7
\end{bmatrix} =
\begin{bmatrix}
6 \\ 14
\end{bmatrix}
$$

In [ ]:
a = 2
u = np.array([[3, 7]])
print(a, end=" = a\n\n")
print(u.T, end=" = u\n\n")
print(a*u.T, end=" = au")

2 = a

[[3]
 [7]] = u

[[ 6]
 [14]] = au

# 3. Dot product
---
Bár a vektorok skaláris szorzása számos tekintetben hasonlít a számok szorzására, lényeges különbség az, hogy míg két szám szorzata ismét szám, két vektor skaláris szorzata nem vektor, hanem szám (skalár, innen ered az elnevezés)

https://hu.wikipedia.org/wiki/Skal%C3%A1ris_szorzat

$$ \large
\vec{u} \cdot \vec{v} = 
\begin{bmatrix}
u_1 \\ u_2 \\ \vdots \\ u_n
\end{bmatrix} \cdot
\begin{bmatrix}
v_1 \\ v_2 \\ \vdots \\ v_n
\end{bmatrix} =
\sum_i^n u_i \cdot v_i
$$

$$ \large
\sum_i^n u_i \cdot v_i =
u_1 \cdot v_1 + u_2 \cdot v_2 + ... + u_n \cdot v_n
$$

Példa:

$$ \large
\vec{u} =
\begin{bmatrix}
3 \\ 7
\end{bmatrix}
\quad , \quad
\vec{v} =
\begin{bmatrix}
2 \\ 5
\end{bmatrix}
$$

$$ \large
\begin{aligned}
\vec{u} \cdot \vec{v} &= 3 \cdot 2 + 7 \cdot 5 \\
&= 6 + 35 \\
&= 41
\end{aligned}
$$

In [ ]:
u = np.array([3, 7])
v = np.array([2, 5])
print(u, end=" = u\n\n")
print(v, end=" = v\n\n")
print(np.dot(u, v), end=" = u.v")

[3 7] = u

[2 5] = v

41 = u.v

## 3.1 Egység vektor
---
Olyan vektor, melynek hossza 1 egység. Tetszőleges, nullától különböző a vektor esetén az vektor egységvektor, amelynek iránya ugyanaz, mint az eredeti a vektoré.

$$ \large
\|\vec{u}\|_2 =
\left[ \sum_i^n u_i^2 \right]^{\frac{1}{2}}=\sqrt{u_1^2+u_2^2+...+u_n^2}
$$

_

$$ \large
\hat{u}=\frac{\vec{u}}{\|\vec{u}\|}
$$


![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_unit_vector.jpg?raw=true)



Példa:

$$ \large
\vec{u} = [3 \quad 4]
$$

$$ \large
\begin{aligned}
\|\vec{u}\| &= \sqrt{3^2+4^2} \\
&= \sqrt{9+16} \\
&= 5
\end{aligned}
$$

$$ \large
\frac{\vec{u}}{\|\vec{u}\|} =
\left[ \frac{3}{5} \quad \frac{4}{5} \right] =
[0.6 \quad 0.8]
$$

In [ ]:
u = np.array([3, 4])
u_ = np.sum(u**2)**0.5
print(u, end=" = u\n\n")
print(u_, end=" = ||u||\n\n")
print(u/u_, end=" = û")

[3 4] = u

5.0 = ||u||

[0.6 0.8] = û

## 3.2. Vektorok között szög
---
A skaláris szorázból adódik, hogy *skaláris szorzás*:


$$ \large
\vec{u} \cdot \vec{v} = \|\vec{u}\| \|\vec{v}\| \cos{\theta}
$$

tehát a bezárt szög,

$$ \large
\theta=\cos^{-1} \frac{\vec{u} \cdot \vec{v}}{\|\vec{u}\| \|\vec{v}\|}
$$

![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_angle.jpg?raw=true)

Például:

$$ \large
\vec{u} =
\begin{bmatrix}
2 \\ 1
\end{bmatrix}
\quad , \quad
\vec{v} =
\begin{bmatrix}
3 \\ 3
\end{bmatrix}
$$

$$ \large
\begin{aligned}
\angle (\vec{u}, \vec{v}) = \theta
&= \arccos \frac{2 \cdot 3 + 1 \cdot 3}{\sqrt{2^2+1^2} \sqrt{3^2+3^2}} \\
&= \arccos \frac{9}{\sqrt{5} \sqrt{18}} \\
&\approx 0.32 \text{rad} \quad \approx 18.43°
\end{aligned}
$$

In [ ]:
u = np.array([2, 1])
v = np.array([3, 3])
uv = np.dot(u, v)
u_ = np.sum(u**2)**0.5
v_ = np.sum(v**2)**0.5
rad = np.arccos(uv/(u_*v_))
print(u, end=" = u\n\n")
print(v, end=" = v\n\n")
print(f'{np.rad2deg(rad):.02f}', end=" = θ")

[2 1] = u

[3 3] = v

18.43 = θ

## 3.3. Párhuzamosság
---
Két vektor **párhuzamos**, $\large \vec{u} // \vec{v}$ ha van olyan $k$ érték amelyel leírható az alábbi egyenlőség:

$$ \large
\vec{u} = k\vec{v}
$$

Másképpen felírva

$$ \large
\frac{u_1}{v_1} = \frac{u_2}{v_2} = ... = \frac{u_n}{v_n} = k
$$

Két vektor párhuzamos, ha elemeik arányosak egymással.

![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_parallel.jpg?raw=true)

Példa:

$$ \large
\vec{u} =
\begin{bmatrix}
2 \\ 3
\end{bmatrix}
\quad , \quad
\vec{v} =
\begin{bmatrix}
6 \\ 9
\end{bmatrix}
$$

$$ \large
\frac{2}{6} = \frac{3}{9} = \frac{1}{3}
$$

In [ ]:
u = np.array([2, 3])
v = np.array([6, 9])
print(u, end=" = u\n\n")
print(v, end=" = v\n\n")
print(f'{u/v}', end=" = k")

[2 3] = u

[6 9] = v

[0.33333333 0.33333333] = k

Két vektor **merőleges, vagy ortogonális** - $\large \vec{u} \bot \vec{v}$ a közöttük lévő $\theta$ szög 90° vagy skaláris szorzatuk 0.

$$ \large
\vec{u} \bot \vec{v} \Rightarrow \vec{u} \cdot \vec{v} = 0
$$


![vectors](https://github.com/JoDeMiro/ImageProcessing/blob/main/images/makrdown/linear-algebra_vectors_orthogonal.jpg?raw=true)


Példa:

$$ \large
\vec{u} =
\begin{bmatrix}
2 \\ 1
\end{bmatrix}
\quad , \quad
\vec{v} =
\begin{bmatrix}
-2 \\ 4
\end{bmatrix}
$$

A skaláris szorzatuk alapján:

$$ \large
\vec{u} \cdot \vec{v} = 2 \cdot (-2) + 1 \cdot 4 = 0
$$

vagy $\theta$ meghatározásával:

$$ \large
\begin{aligned}
\angle (\vec{u}, \vec{v}) = \theta
&= \arccos \frac{2 \cdot (-2) + 1 \cdot 4}{\sqrt{2^2+1^2} \sqrt{(-2)^2+4^2}} \\
&= \arccos \frac{0}{\sqrt{5} \sqrt{20}} \\
&\approx 1.57 \text{rad} \quad = 90°
\end{aligned}
$$

In [ ]:
u = np.array([2, 1])
v = np.array([-2, 4])
uv = np.dot(u, v)
u_ = np.sum(u**2)**0.5
v_ = np.sum(v**2)**0.5
rad = np.arccos(uv/(u_*v_))
print(u, end=" = u\n\n")
print(v, end=" = v\n\n")
print(uv, end=" = u.v\n\n")
print(f'{np.rad2deg(rad):.02f}', end=" = θ")

[2 1] = u

[-2  4] = v

0 = u.v

90.00 = θ


<a name="felhasznalt-irodalom"></a>

[vissza a tartalomhoz](#tartalom)

<a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>

## Felhasznált irodalom és internetes cimek <a href="#tartalom"><font color='white'>&nbsp;&nbsp;&nbsp;&nbsp;Main page</font></a>


Wikipedia - 'Skaláris szorzat'
<br>
https://hu.wikipedia.org/wiki/Skal%C3%A1ris_szorzat


Vektor
<br>
https://www.mimi.hu/matematika/derivalt.html#maintitle


BME - Fizika Tanszék - Előadás anyag
<br>
http://www.fke.bme.hu/oktatas/kornyezetMernok/vektorok.pdf


Math is Fun - Vectors
<br>
https://www.mathsisfun.com/algebra/vectors.html


Wikipedia - 'Euclidean Vector'
<br>
https://en.wikipedia.org/wiki/Euclidean_vector

